### ISSUE TITLE
YUI CSS Compression fails with version 5.0.2

### ISSUE THREAD

**Issue by volontarian** [joliss/jquery-ui-rails#86]
YUI CSS Compression fails with version 5.0.2 at assets precompilation process.

I created a sample application to reproduce the error: https://github.com/gawlista/jquery-ui-rails-5-compression-fails
There are 2 commits: 
* [first commit includes the Rails generator results](https://github.com/gawlista/jquery-ui-rails-5-compression-fails/commit/01c615df73f0ebd6e69a1fd98e2a0cd6628f7c7b) and 
* [second commit includes customization which let css compression fail](https://github.com/gawlista/jquery-ui-rails-5-compression-fails/commit/1a3d0bb902039001642d6cea3ae9553dcc114414).

You get the Error with the following command:

RAILS_ENV=staging RAILS_GROUPS=assets bundle exec rake assets:precompile --trace

    administorsmini:jquery-ui-rails-5-compression-fails gawlim$ RAILS_ENV=staging RAILS_GROUPS=assets bundle exec rake assets:precompile --trace
    ** Invoke assets:precompile (first_time)
    ** Invoke assets:environment (first_time)
    ** Execute assets:environment
    ** Invoke environment (first_time)
    ** Execute environment
    ** Execute assets:precompile
    rake aborted!
    YUI::Compressor::RuntimeError: compression failed
      (in /Users/gawlim/workspace/reproduction/jquery-ui-rails-5-compression-fails/app/assets/stylesheets/application.css.sass)
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:87:in `block in compress'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:117:in `streamify'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/yui-compressor-0.9.6/lib/yui/compressor.rb:66:in `compress'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/yui_compressor.rb:21:in `evaluate'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:197:in `block in evaluate'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `each'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `evaluate'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/bundled_asset.rb:25:in `initialize'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:377:in `new'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:377:in `build_asset'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:94:in `block in build_asset'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/caching.rb:58:in `cache_asset'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:93:in `build_asset'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:287:in `find_asset'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:61:in `find_asset'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:257:in `benchmark'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:210:in `find_asset'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:119:in `block in compile'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `each'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `compile'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.2.0/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-2.11.3/lib/rake/sprocketstask.rb:146:in `with_logger'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.2.0/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
    /Users/gawlim/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
    /Users/gawlim/.rbenv/versions/2.1.1/bin/rake:23:in `load'
    /Users/gawlim/.rbenv/versions/2.1.1/bin/rake:23:in `<main>'
    Tasks: TOP => assets:precompile

With a application.css like this instead of a Sass file it still fails like before:

    *= require_tree .
    *= require jquery-ui
    *= require_self

How to handle this?

**Comment by volontarian** [comment]
I've updated the yui-compressor gem to latest version 0.12.0. Now it works :-)
