### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by kalashnikovisme** [joliss/jquery-ui-rails#87]
Rails 4.1.7
Jquery-ui-rails 5.0.2

Trace:

```
ExecJS::ProgramError - TypeError: Cannot read property '1' of null
  (in /home/pavel/.rvm/gems/ruby-2.1.2/gems/jquery-ui-rails-5.0.2/app/assets/stylesheets/jquery-ui/all.css.erb):
  execjs (2.2.2) lib/execjs/ruby_racer_runtime.rb:49:in `rescue in block in call'
  execjs (2.2.2) lib/execjs/ruby_racer_runtime.rb:43:in `block in call'
  execjs (2.2.2) lib/execjs/ruby_racer_runtime.rb:78:in `block in lock'
  execjs (2.2.2) lib/execjs/ruby_racer_runtime.rb:76:in `lock'
  execjs (2.2.2) lib/execjs/ruby_racer_runtime.rb:42:in `call'
  autoprefixer-rails (4.0.0) lib/autoprefixer-rails/processor.rb:19:in `process'
  autoprefixer-rails (4.0.0) lib/autoprefixer-rails/sprockets.rb:16:in `process'
  autoprefixer-rails (4.0.0) lib/autoprefixer-rails/sprockets.rb:22:in `block in install'
  sprockets (2.11.3) lib/sprockets/processor.rb:29:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
  sprockets (2.11.3) lib/sprockets/context.rb:197:in `block in evaluate'
  sprockets (2.11.3) lib/sprockets/context.rb:194:in `evaluate'
  sprockets (2.11.3) lib/sprockets/processed_asset.rb:12:in `initialize'
  sprockets (2.11.3) lib/sprockets/base.rb:374:in `block in build_asset'
  sprockets (2.11.3) lib/sprockets/base.rb:395:in `circular_call_protection'
  sprockets (2.11.3) lib/sprockets/base.rb:373:in `build_asset'
  sprockets (2.11.3) lib/sprockets/index.rb:94:in `block in build_asset'
  sprockets (2.11.3) lib/sprockets/caching.rb:58:in `cache_asset'
  sprockets (2.11.3) lib/sprockets/index.rb:93:in `build_asset'
  sprockets (2.11.3) lib/sprockets/base.rb:287:in `find_asset'
  sprockets (2.11.3) lib/sprockets/index.rb:61:in `find_asset'
  sprockets (2.11.3) lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
  sprockets (2.11.3) lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
  sprockets (2.11.3) lib/sprockets/processed_asset.rb:97:in `build_required_assets'
  sprockets (2.11.3) lib/sprockets/processed_asset.rb:16:in `initialize'
  sprockets (2.11.3) lib/sprockets/base.rb:374:in `block in build_asset'
  sprockets (2.11.3) lib/sprockets/base.rb:395:in `circular_call_protection'
  sprockets (2.11.3) lib/sprockets/base.rb:373:in `build_asset'
  sprockets (2.11.3) lib/sprockets/index.rb:94:in `block in build_asset'
  sprockets (2.11.3) lib/sprockets/caching.rb:58:in `cache_asset'
  sprockets (2.11.3) lib/sprockets/index.rb:93:in `build_asset'
  sprockets (2.11.3) lib/sprockets/base.rb:287:in `find_asset'
  sprockets (2.11.3) lib/sprockets/index.rb:61:in `find_asset'
  sprockets (2.11.3) lib/sprockets/bundled_asset.rb:16:in `initialize'
  sprockets (2.11.3) lib/sprockets/base.rb:377:in `build_asset'
  sprockets (2.11.3) lib/sprockets/index.rb:94:in `block in build_asset'
  sprockets (2.11.3) lib/sprockets/caching.rb:58:in `cache_asset'
  sprockets (2.11.3) lib/sprockets/index.rb:93:in `build_asset'
  sprockets (2.11.3) lib/sprockets/base.rb:287:in `find_asset'
  sprockets (2.11.3) lib/sprockets/index.rb:61:in `find_asset'
  sprockets (2.11.3) lib/sprockets/environment.rb:75:in `find_asset'
  sprockets (2.11.3) lib/sprockets/base.rb:295:in `[]'
  sprockets-rails (2.2.0) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
  sprockets-rails (2.2.0) lib/sprockets/rails/helper.rb:160:in `block in stylesheet_link_tag'
  sprockets-rails (2.2.0) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
  app/views/layouts/_head_content.html.erb:104:in `_app_views_layouts__head_content_html_erb__1672844728782157414_63190840'
  actionview (4.1.7) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.7) lib/active_support/notifications.rb:161:in `instrument'
  actionview (4.1.7) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.7) lib/action_view/template.rb:143:in `render'
  actionview (4.1.7) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
  actionview (4.1.7) lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
  actionview (4.1.7) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.7) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.7) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.7) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.7) lib/action_view/renderer/partial_renderer.rb:278:in `render'
  actionview (4.1.7) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.1.7) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  haml (4.0.5) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_html_erb___2303719101742042752_70270000'
  actionview (4.1.7) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.7) lib/active_support/notifications.rb:161:in `instrument'
  actionview (4.1.7) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.7) lib/action_view/template.rb:143:in `render'
  actionview (4.1.7) lib/action_view/renderer/template_renderer.rb:67:in `render_with_layout'
  actionview (4.1.7) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.7) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.7) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.7) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.7) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.7) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.7) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.7) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.7) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.7) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.7) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.1.7) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/pavel/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.1.7) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.1.7) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:40:in `render'
  actionpack (4.1.7) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.1.7) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.1.7) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.7) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.7) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.7) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.7) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.7) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.7) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.7) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.7) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.7) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.7) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.7) lib/action_view/rendering.rb:30:in `process'
  session_off (0.5.1) lib/session_off.rb:176:in `process_with_session_off'
  actionpack (4.1.7) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.7) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.7) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.7) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.7) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.7) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.7) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.7) lib/action_dispatch/routing/route_set.rb:678:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.7) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.7) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.7) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.7) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.7) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.7) lib/rails/engine.rb:514:in `call'
  railties (4.1.7) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.2) lib/rack/server.rb:264:in `start'
  railties (4.1.7) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.7) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.7) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.7) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.7) lib/rails/commands.rb:17:in `<top (required)>'
  script/rails:6:in `<main>'
```

Can you help me?

**Comment by rosenfeld** [comment]
Could you please provide a sample Rails application demonstrating the issue so that we could reproduce it?

**Comment by rosenfeld** [comment]
I'll close this ticket to clean up our manageable issues. Once you have a sample application demonstrating the issue so we can work on it please let us know and I'll reopen the ticket.
